package SeleniumTest;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class SysTest001QicFixCT401ClientTowLoginSunny002Test {
	
  private ChromeDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  
    driver = new ChromeDriver(); 
    
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    ((WebDriver) driver).quit();
  }
  @Test
  public void sysTest001QicFixCT401ClientTowLoginSunny002() {	
		
    driver.get("http://cen4072-fa20.cs.fiu.edu:8080/QicFixSystem-Geordi/login.jsp");
    driver.manage().window().setSize(new Dimension(786, 824));
    driver.findElement(By.id("inputEmail")).sendKeys("user1@email.com");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("ge6SgZ3rbEFs95Cg");
    driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
  }
}
